/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package party_lists;

import Stud_Dashboard.Stud_Dashboard;

/**
 *
 * @author Administrator
 */
public class p_lists extends javax.swing.JFrame {

    /**
     * Creates new form p_lists
     */
    public p_lists() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        party_lists = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_opl = new javax.swing.JButton();
        op_pic = new javax.swing.JLabel();
        op_pl = new javax.swing.JLabel();
        db_pic = new javax.swing.JLabel();
        db_pl = new javax.swing.JLabel();
        btn_dbl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 417));
        setPreferredSize(new java.awt.Dimension(500, 417));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(35, 59, 118));
        jPanel2.setPreferredSize(new java.awt.Dimension(1498, 837));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo 83x80.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 80));

        btn_back.setBackground(new java.awt.Color(196, 39, 58));
        btn_back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel2.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, 100, 40));

        party_lists.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        party_lists.setForeground(new java.awt.Color(255, 255, 255));
        party_lists.setText("PARTYLIST SECTION");
        jPanel2.add(party_lists, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jButton1.setBackground(new java.awt.Color(17, 128, 14));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Proceed");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 20, 100, 40));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, -1, -1));

        btn_opl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_opl.setText("Click to View");
        btn_opl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oplActionPerformed(evt);
            }
        });
        jPanel2.add(btn_opl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 170, -1));

        op_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/One-Piece-Logo (1).png"))); // NOI18N
        jPanel2.add(op_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, 260));

        op_pl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        op_pl.setForeground(new java.awt.Color(255, 255, 255));
        op_pl.setText("ONE PIECE PARTYLIST");
        jPanel2.add(op_pl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        db_pic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logo-dragon-ball-removebg-previe.png"))); // NOI18N
        jPanel2.add(db_pic, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, -1, -1));

        db_pl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        db_pl.setForeground(new java.awt.Color(255, 255, 255));
        db_pl.setText("DRAGON BALL PARTYLIST");
        jPanel2.add(db_pl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 479, -1, 30));

        btn_dbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_dbl.setText("Click to View");
        jPanel2.add(btn_dbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 170, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 860));

        setSize(new java.awt.Dimension(1176, 771));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        this.setVisible(false);
        new Stud_Dashboard().setVisible(true);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_oplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oplActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_oplActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(p_lists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(p_lists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(p_lists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(p_lists.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new p_lists().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_dbl;
    private javax.swing.JButton btn_opl;
    private javax.swing.JLabel db_pic;
    private javax.swing.JLabel db_pl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel op_pic;
    private javax.swing.JLabel op_pl;
    private javax.swing.JLabel party_lists;
    // End of variables declaration//GEN-END:variables
}
